export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const VERIFY_TOKEN = "VERIFY_TOKEN";
export const VERIFY_TOKEN_ERROR = "VERIFY_TOKEN_ERROR";

export const LOGOUT = "LOGOUT";

export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const CREATE_PRODUCT_ERROR = "CREATE_PRODUCT_ERROR";

export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const FETCH_ALL_PRODUCTS = "FETCH_ALL_PRODUCTS";
export const FETCH_ALL_PRODUCTS_ERROR = "FETCH_ALL_PRODUCTS_ERROR";

export const FETCH_PRODUCT_DETAILS_BY_ID = "FETCH_PRODUCT_DETAILS_BY_ID";
export const FETCH_PRODUCT_DETAILS_BY_ID_ERROR =
  "FETCH_PRODUCT_DETAILS_BY_ID_ERROR";

export const FETCH_PRODUCTS_BY_DISTRIBUTOR_ID =
  "FETCH_PRODUCTS_BY_DISTRIBUTOR_ID";
export const FETCH_PRODUCTS_BY_DISTRIBUTOR_ID_ERROR =
  "FETCH_PRODUCTS_BY_DISTRIBUTOR_ID_ERROR";

export const FETCH_ALL_DISTRIBUTORS = "FETCH_ALL_DISTRIBUTORS";
export const FETCH_ALL_DISTRIBUTORS_ERROR = "FETCH_ALL_DISTRIBUTORS_ERROR";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const FETCH_ORDER = "FETCH_ORDER";
export const FETCH_ORDER_ERROR = "FETCH_ORDER_ERROR";

export const CREATE_ORDER = "CREATE_ORDER";
export const CREATE_ORDER_ERROR = "CREATE_ORDER_ERROR";

export const UPDATE_ORDER_ID = "UPDATE_ORDER_DETAILS";
export const UPDATE_ORDER_ID_ERROR = "UPDATE_ORDER_DETAILS_ERROR";

export const GET_TOTAL_SALE = "GET_TOTAL_SALE";
export const GET_TOTAL_SALE_ERROR = "GET_TOTAL_SALE_ERROR";

export const GET_SALE_BY_RETAILER = "GET_SALE_BY_RETAILER";
export const GET_SALE_BY_RETAILER_ERROR = "GET_SALE_BY_RETAILER_ERROR";

export const GET_SALE_BETWEEN_DATES = "GET_SALE_BETWEEN_DATES";
export const GET_SALE_BETWEEN_DATES_ERROR = "GET_SALE_BETWEEN_DATES_ERROR";

export const GET_ALL_RETAILERS = "GET_ALL_RETAILERS";
export const GET_ALL_RETAILER_ERROR = "GET_ALL_RETAILERS_ERROR";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const REGISTRATION_FAIL = "REGISTRATION_FAIL";

export const REGISTER_DISTRIBUTOR = "REGISTER_DISTRIBUTOR";
export const REGISTER_DISTRIBUTOR_ERROR = "REGISTER_DISTRIBUTOR_ERROR";
